/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import estuctural.Ciudadano;
import estuctural.Delito;
import java.rmi.RemoteException;
import javax.swing.table.DefaultTableModel;
import model.IServiciosAntecedentesPenales;

/**
 *
 * @author Estudiantes
 */
public class GUIMostrarDelito extends javax.swing.JFrame {

    private IServiciosAntecedentesPenales controller;
    private IBuscarDelito ventanaObjetivo;
    /**
     * Creates new form GUIMostrarDelito
     */
    public GUIMostrarDelito(IServiciosAntecedentesPenales controller, IBuscarDelito buscarDelito) {
        initComponents();
        this.controller = controller;
        ventanaObjetivo= buscarDelito;
        llenarGrilla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDelitos = new javax.swing.JTable();

        setTitle("Delitos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jTableDelitos.setBackground(new java.awt.Color(229, 229, 229));
        jTableDelitos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jTableDelitos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Pena_Minima", "Pena_Maxima"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDelitos.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTableDelitos.setSelectionForeground(new java.awt.Color(3, 59, 118));
        jTableDelitos.getTableHeader().setReorderingAllowed(false);
        jTableDelitos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDelitosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableDelitos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableDelitosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDelitosMouseClicked
        // TODO add your handling code here:
        int row = jTableDelitos.getSelectedRow();
        int codigo = (Integer)jTableDelitos.getValueAt(row, 0);
        try {
            Delito delito = controller.darDelitoPorCodigo(codigo);
            ventanaObjetivo.cambiarTxtDelito(codigo);
            this.dispose();
        } catch (RemoteException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jTableDelitosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableDelitos;
    // End of variables declaration//GEN-END:variables

    private void llenarGrilla()
    {
         try {
            DefaultTableModel model = (DefaultTableModel) jTableDelitos.getModel();
            model.getDataVector().removeAllElements();
            if(!controller.darDelitos().isEmpty())
            {
                for (Delito delito : controller.darDelitos()) {
                    model.addRow(new Object[]{delito.getCodigo(),delito.getNombre(), delito.getPenaMinima(), delito.getPenaMaxima()});
                }    
            }
            
        } catch (RemoteException ex) {
             System.out.println(ex.getMessage());
        }
    }
}
